title: "UCSB CS/CE Undergrad Alumni and Student Profiles"
github_url: https://github.com/ucsb-cs-ce-profiles/ucsb-cs-ce-profiles.github.io

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:

  students:
    output: true
    permalink: /students/:path/

  alumni:
    output: true
    permalink: /alumni/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: students
    values:
      layout: person

  - scope:
      path: ""
      type: alumni
    values:
      layout: person

 

